WDB-84/confirm email page
kibartas/PSK pull request #13
Opened 2021-04-26 12:22 UTC by tmaciulis22

![image](https://user-images.githubusercontent.com/29150754/116081672-37bdd580-a6a3-11eb-8c57-d3737fa6148f.png)

2021-04-26 13:30 UTC, AArlauskas approved these changes
I would consider one renaming, but besides that, looks good

2021-04-26 13:30 UTC, AArlauskas commented on frontend/src/components/ConfirmEmailCard/ConfirmEmailCard.js
> +          src={confirmEmailIll}
I get how you named it, but it looks confusing

2021-04-27 11:30 UTC, kibartas requested changes
Are you gonna implement destructuring? I thought this PR was supposed to include it. Other than that, LGTM

2021-04-27 11:30 UTC, kibartas commented on frontend/src/App.js
> +          <Route exact path="/register" component={RegisterPage} />
Odd one out?

2021-04-27 11:38 UTC, merged